login: &login
  adapter: mysql2
  username: root
  password:
  endcoding: utf8
  reconnect: true
  # socket: /tmp/mysql.sock
  host: 127.0.0.1
  port: 31313

workflow_development:
  <<: *login
  database: workflow_db_development

regenerate:
  <<: *login
  database: workflow_db_regenerate

development:
  <<: *login
  database: workflow_db_development
test:
  <<: *login
  database: workflow_db_test
